### ISSUE TITLE
Dependency issue - tmtoolkit's v0.11.2 works, but latest v0.12.0 does not work

### ISSUE THREAD

**Issue by lingeringcode** [browndw/docuscospacy#1]
Hello!

When I used the `coll_table` function, as seen in the code snippet below, I received the following `AttributeError` in relation to one of `docuscospacy`'s dependencies: `tmtoolkit`.

```python
ct_relationships = coll_table(
  tp, 
  'relationships',
  l_span=3,
  r_span=3,
  node_tag='NN2', 
  statistic='pmi', 
  count_by='pos'
)
```

Error print out:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[33], line 1
----> 1 ct_relationships = coll_table(
      2   tp, 
      3   'relationships',
      4   l_span=3,
      5   r_span=3,
      6   node_tag='NN2', 
      7   statistic='pmi', 
      8   count_by='pos'
      9 )

File [~/brew/lib/python3.9/site-packages/docuscospacy/corpus_analysis.py:250](https://file+.vscode-resource.vscode-cdn.net/Users/chrislindgren/Documents/VT/pubs/swr-citation/notebooks/analysis/textual/~/brew/lib/python3.9/site-packages/docuscospacy/corpus_analysis.py:250), in coll_table(tok, node_word, l_span, r_span, statistic, count_by, node_tag, tag_ignore)
    247     df = pd.merge(df_span, df_total, how='inner', on=['Token', 'Tag'])
    248 if statistic=='pmi':
    249     # Fix error from tmtoolkit's pmi()
--> 250     df['MI'] = pmi(node_freq, df['Freq Total'], df['Freq Span'], sum(df_total['Freq Total']), normalize=False)
    251 if statistic=='npmi':
    252     df['MI'] = pmi(node_freq, df['Freq Total'], df['Freq Span'], sum(df_total['Freq Total']), normalize=True)

File [~/brew/lib/python3.9/site-packages/tmtoolkit/tokenseq/_metrics.py:62](https://file+.vscode-resource.vscode-cdn.net/Users/chrislindgren/Documents/VT/pubs/swr-citation/notebooks/analysis/textual/~/brew/lib/python3.9/site-packages/tmtoolkit/tokenseq/_metrics.py:62), in pmi(x, y, xy, n_total, logfn, k, alpha, normalize)
     59 if k > 1 and normalize:
     60     raise ValueError('normalization is only implemented for standard PMI with `k=1`')
---> 62 if x.ndim == 1:
     63     if y is None or xy is None or x.shape != y.shape or x.shape != xy.shape:
     64         raise ValueError('if `x` is given as vector, `y` and `xy` must also be given and must have the same length')

AttributeError: 'int' object has no attribute 'ndim'
```

It seems that tmtoolkit's latest 0.12.0 version made some significant changes and has archived the repo that this project currently points to, which has impacted in this instance the call to one of their 'metrics' functions: `pmi()`. With regards to this 'pmi()' function, it looks like the architecture of the file(s) and this function's arguments have changed between versions:

- [v0.11.2 - tmtoolkit/tokenseq.py](https://github.com/WZBSocialScienceCenter/tmtoolkit/blob/master/tmtoolkit/tokenseq.py#L186C1-L187C45): `def pmi(x: np.ndarray, y: np.ndarray, xy: np.ndarray, n_total: Optional[int] = None, logfn: Callable = np.log, k: int = 1, normalize: bool = False)`
- [v0.12.0 - tmtoolkit/tokenseq/_metrics.py](https://github.com/internaut/tmtoolkit/blob/master/tmtoolkit/tokenseq/_metrics.py#L19): `pmi(x: Union[np.ndarray, sparse.spmatrix], y: Optional[np.ndarray] = None, xy: Optional[np.ndarray] = None, n_total: Optional[int] = None, logfn: Callable = np.log, k: int = 1, alpha: float = 1.0, normalize: bool = False)`

Perhaps a temporary solution is to add `tmtoolkit` to `requirements.txt`: `tmtoolkit==0.11.2`. That worked for me.

Thank you for this wonderful and very helpful tool! I really appreciate it and hope this is helpful.

**Comment by browndw** [comment]
Thanks for this. Yes, I caught this, as well. I need to update the package to resolve this issue. The new tmtoolkit version has caused a few problems. My goal is to get a new version pushed next week.

**Comment by browndw** [comment]
> Hello!
> 
> When I used the `coll_table` function, as seen in the code snippet below, I received the following `AttributeError` in relation to one of `docuscospacy`'s dependencies: `tmtoolkit`.
> 
> ```python
> ct_relationships = coll_table(
>   tp, 
>   'relationships',
>   l_span=3,
>   r_span=3,
>   node_tag='NN2', 
>   statistic='pmi', 
>   count_by='pos'
> )
> ```
> 
> Error print out:
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[33], line 1
> ----> 1 ct_relationships = coll_table(
>       2   tp, 
>       3   'relationships',
>       4   l_span=3,
>       5   r_span=3,
>       6   node_tag='NN2', 
>       7   statistic='pmi', 
>       8   count_by='pos'
>       9 )
> 
> File [~/brew/lib/python3.9/site-packages/docuscospacy/corpus_analysis.py:250](https://file+.vscode-resource.vscode-cdn.net/Users/chrislindgren/Documents/VT/pubs/swr-citation/notebooks/analysis/textual/~/brew/lib/python3.9/site-packages/docuscospacy/corpus_analysis.py:250), in coll_table(tok, node_word, l_span, r_span, statistic, count_by, node_tag, tag_ignore)
>     247     df = pd.merge(df_span, df_total, how='inner', on=['Token', 'Tag'])
>     248 if statistic=='pmi':
>     249     # Fix error from tmtoolkit's pmi()
> --> 250     df['MI'] = pmi(node_freq, df['Freq Total'], df['Freq Span'], sum(df_total['Freq Total']), normalize=False)
>     251 if statistic=='npmi':
>     252     df['MI'] = pmi(node_freq, df['Freq Total'], df['Freq Span'], sum(df_total['Freq Total']), normalize=True)
> 
> File [~/brew/lib/python3.9/site-packages/tmtoolkit/tokenseq/_metrics.py:62](https://file+.vscode-resource.vscode-cdn.net/Users/chrislindgren/Documents/VT/pubs/swr-citation/notebooks/analysis/textual/~/brew/lib/python3.9/site-packages/tmtoolkit/tokenseq/_metrics.py:62), in pmi(x, y, xy, n_total, logfn, k, alpha, normalize)
>      59 if k > 1 and normalize:
>      60     raise ValueError('normalization is only implemented for standard PMI with `k=1`')
> ---> 62 if x.ndim == 1:
>      63     if y is None or xy is None or x.shape != y.shape or x.shape != xy.shape:
>      64         raise ValueError('if `x` is given as vector, `y` and `xy` must also be given and must have the same length')
> 
> AttributeError: 'int' object has no attribute 'ndim'
> ```
> 
> It seems that tmtoolkit's latest 0.12.0 version made some significant changes and has archived the repo that this project currently points to, which has impacted in this instance the call to one of their 'metrics' functions: `pmi()`. With regards to this 'pmi()' function, it looks like the architecture of the file(s) and this function's arguments have changed between versions:
> 
>     * [v0.11.2 - tmtoolkit/tokenseq.py](https://github.com/WZBSocialScienceCenter/tmtoolkit/blob/master/tmtoolkit/tokenseq.py#L186C1-L187C45): `def pmi(x: np.ndarray, y: np.ndarray, xy: np.ndarray, n_total: Optional[int] = None, logfn: Callable = np.log, k: int = 1, normalize: bool = False)`
> 
>     * [v0.12.0 - tmtoolkit/tokenseq/_metrics.py](https://github.com/internaut/tmtoolkit/blob/master/tmtoolkit/tokenseq/_metrics.py#L19): `pmi(x: Union[np.ndarray, sparse.spmatrix], y: Optional[np.ndarray] = None, xy: Optional[np.ndarray] = None, n_total: Optional[int] = None, logfn: Callable = np.log, k: int = 1, alpha: float = 1.0, normalize: bool = False)`
> 
> 
> Perhaps a temporary solution is to add `tmtoolkit` to `requirements.txt`: `tmtoolkit==0.11.2`. That worked for me.
> 
> Thank you for this wonderful and very helpful tool! I really appreciate it and hope this is helpful.

Thanks for this. Yes, I caught this, as well. I need to update the package to resolve this issue. The new **tmtoolkit** version has caused a few problems. My goal is to get a new version pushed next week.

**Comment by browndw** [comment]
I finally have this resolved. With the updated version (0.2.4), there are now 2 ways of normalizing document-term matrices. You can use a package function `normalize_dtm` (for example: `normalize_dtm(tm, scheme='prop')`) and the scheme can be set to either **prop** or **tfidf**. Alternatively, the dtm can be converted to COO format, which is used by the latest version of **tmtoolkit**: `tags_coo, docs, vocab = dtm_to_coo(tm)`. In that format, the `tf_proportions` function (and other ones) will work.
