### ISSUE TITLE
tmtoolkit dependency issue: `tf_proportions()` uses deprecated pandas support of multi-dimensional indexing

### ISSUE THREAD

**Issue by lingeringcode** [browndw/docuscospacy#2]
I needed to modify the use of `tf_proportions()`—a function from `tmtoolkit` (0.11.2) `bow_stats.py`, line 160, `dtm`. Specifically, I needed to modify tmtoolkit's code: `norm_factor = 1 / doc_lengths(dtm)[:, None]   # shape: Nx1`. (`tmtoolkit/bow/bow_stats.py:160`, in tf_proportions(dtm))

This code yielded the following error related to converting a matrix to a numpy object for pandas support:

```
ValueError                                Traceback (most recent call last)
Cell In[42], line 1
----> 1 tf_proportions(tm).head(10)

File ~/brew/lib/python3.9/site-packages/tmtoolkit/bow/bow_stats.py:160, in tf_proportions(dtm)
    157 if dtm.ndim != 2:
    158     raise ValueError('`dtm` must be a 2D array/matrix')
--> 160 norm_factor = 1 / doc_lengths(dtm)[:, None]   # shape: Nx1
    162 if issparse(dtm):
    163     res = dtm.multiply(norm_factor)

File ~/brew/lib/python3.9/site-packages/pandas/core/series.py:1033, in Series.__getitem__(self, key)
   1030     key = np.asarray(key, dtype=bool)
   1031     return self._get_values(key)
-> 1033 return self._get_with(key)

File ~/brew/lib/python3.9/site-packages/pandas/core/series.py:1048, in Series._get_with(self, key)
   1043     raise TypeError(
   1044         "Indexing a Series with DataFrame is not "
   1045         "supported, use the appropriate DataFrame column"
   1046     )
   1047 elif isinstance(key, tuple):
-> 1048     return self._get_values_tuple(key)
   1050 elif not is_list_like(key):
...
    344         "Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer "
    345         "supported. Convert to a numpy array before indexing instead."
    346     )

ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.
```

**MODIFIED**: `norm_factor = 1 / doc_lengths(dtm.to_numpy())[:, None]   # shape: Nx1`

This resolved the issue on my end, but is obviously not a good long-term solution. I know that this particular issue is fuzzy as well, since it required me to modify `tmtoolkit`. Yet, I hope this report is helpful with regards to the `tmtoolkit` dependency, since it is the [second issue](https://github.com/browndw/docuscospacy/issues/1) with the use of an older version of `tmtoolkit` (`0.11.2`), which has since been refactored in `0.12.0`.

Thank you, again, for this module!

**Comment by browndw** [comment]
I finally have this resolved. With the updated version (0.2.4), there are now 2 ways of normalizing document-term matrices. You can use a package function `normalize_dtm` (for example: `normalize_dtm(tm, scheme='prop')`) and the scheme can be set to either **prop** or **tfidf**. Alternatively, the dtm can be converted to COO format, which is used by the latest version of **tmtoolkit**: `tags_coo, docs, vocab = dtm_to_coo(tm)`. In that format, the `tf_proportions` function (and other ones) will work.
